S3 file upload feature
Mate2xo/THP-Creeons_la_coop pull request #157
Opened 2019-08-28 22:15 UTC by Lodi2244

Alors cette fameuse PR ce qui est done : 
- le form d'upload des documents 
- l'index des documents avec preview des fichiers
Ce qu'il reste à faire : 
- les tests
- un peu d'ajax pour afficher directement les fichiers uploader dans le tableau
- un peu de js pur pour faire en sorte que le redirect au save du fichier renvoi sur la tab documents
Et faut prier pour que ça passe en prod aussi 😄 
Enjoy !

2019-09-03 14:10 UTC, Mate2xo commented
J'ai trouvé un bug `ActionController::UnknownFormat in LibrairiesController#show` en essayant d'uploader un document qui n'est pas un PDF (c'était un fichier texte basique)

2019-09-03 16:00 UTC, Mate2xo requested changes
Pour l'instant, il faudrait surtout mettre la gem 'erd' dans le groupe `development`.
Le reste c'est du detail, et on pourra faire un point ensemble.
Merci

2019-09-03 16:00 UTC, Mate2xo commented on Gemfile
> +gem 'erd', '~> 0.6.3'
Pourrais-tu déplacer la gem 'erd' dans le groupe `development` stp?

2019-09-03 16:00 UTC, Mate2xo commented on Gemfile
> -gem 'jbuilder', '~> 2.5'
j'ai besoin de la gem jbuilder pour la generation de JSON pour le calendrier des missions. Il faudrait la remettre stp

2019-09-03 16:00 UTC, Mate2xo commented on app/controllers/libraries_controller.rb
> +    if current_member.role == "super_admin" || current_member.role == "admin"
Tu peux utiliser les helper `admin?` et `super_admin?` pour vérifier les roles
(les helpers sont définis dans `application_controller.rb`)

2019-09-03 16:00 UTC, Mate2xo commented on app/controllers/libraries_controller.rb
> +    if current_member.role == "super_admin" || current_member.role == "admin"
`if admin? || super_admin?`

2019-09-03 16:00 UTC, Mate2xo commented on app/controllers/libraries_controller.rb
> +    if current_member.role == "super_admin" || current_member.role == "admin"
`if admin? || super_admin?`

2019-09-03 16:00 UTC, Mate2xo commented on app/controllers/libraries_controller.rb
> +class LibrariesController < ApplicationController
Les actions #index et #new ne sont pas accessibles via le browser : pas de template `librairies/index.html` et `libraries/new.html` étant donné que tu les render déjà en _partial via le `infos_controller.rb`, et pas de param dispo pour #new.
Est-ce que tu penses utiliser ces actions pour autre chose? Je suppose que c'est pour l'AJAX des documents?

2019-09-03 16:00 UTC, Mate2xo commented on app/views/libraries/_index.html.erb
> +    <% @libraries.each do |lib| %>
passe `@librairies` directement dans les `locals: ` de l'appel du _partial stp (plus explicite).
Actuellement, tu lui passe `@library` mais je ne le vois pas appellé ici.

2019-09-03 16:00 UTC, Mate2xo commented on app/views/libraries/_new.html.erb
> +  <%= form_for @library, { url: libraries_url, method: 'POST' }  do |form|%>
Tu passes déjà `@library` dans les `locals: ` de l'appel du _partial.
Remplaces donc `@library` par `library` stp (pour la cohérence)

2019-09-03 16:00 UTC, Mate2xo commented on package.json
> +    "jquery-stickytabs": "^1.2.4"
C'est quelque chose que tu as rajouté? Ou ça s'est mis avec le `npm install`?

2019-09-03 16:55 UTC, Mate2xo commented on Gemfile
> +gem 'image_processing', '~> 1.9', '>= 1.9.3'
Pour quoi est utilisée cette gem?

2019-09-03 16:58 UTC, Mate2xo commented
Renommer le model `Library` en `Document` serait peut-être plus cohérent en fait, étant donné qu'on l'appelle ainsi dans les vues naturellement. Cela fait plus de sens aussi au pluriel (`documents` vs `librairies`) étant donné que des "librairies" donnent l'impressions que ce se sont des contenants ayant eux-même plusieurs documents.

2019-09-04 08:17 UTC, Lodi2244 commented on Gemfile
> +gem 'erd', '~> 0.6.3'
Yes j'y ai pas pensé my bad

2019-09-04 08:20 UTC, Lodi2244 commented on Gemfile
> -gem 'jbuilder', '~> 2.5'
ça c'est pas normal je n'ai rien supprimé du Gemfile juste ajouté erd et jquery stickytabs 🤔

2019-09-04 08:27 UTC, Lodi2244 commented on app/controllers/libraries_controller.rb
> +    if current_member.role == "super_admin" || current_member.role == "admin"
Oui sorry j'ai juste créé mon controller Libraries sur la base de celui d'Infos comme il n'a pas encore été cleané mais c'est prévu 😉

2019-09-04 08:28 UTC, Lodi2244 commented on app/controllers/libraries_controller.rb
> +class LibrariesController < ApplicationController
Exactement 🙂

2019-09-04 08:31 UTC, Lodi2244 commented on package.json
> +    "jquery-stickytabs": "^1.2.4"
C'est un plugins que j'ai installé via npm  effectivement pour gérer le fait de rester sur la tab active au redirect mais je n'ai pas encore réussi à le faire marcher

2019-09-04 08:34 UTC, Lodi2244 commented on Gemfile
> +gem 'image_processing', '~> 1.9', '>= 1.9.3'
C'est pour la gestion des variants  Active Storage (la customisation du format et du style des images)

2019-09-04 08:39 UTC, Lodi2244 commented on app/views/libraries/_new.html.erb
> +  <%= form_for @library, { url: libraries_url, method: 'POST' }  do |form|%>
D'accord (je n'avais jamais utilisé le render partial avec l'option locals donc je ne savais pas que ma variable était accessible directement dans ma partial ensuite) je vais modifier ça

2019-09-04 08:42 UTC, Lodi2244 commented on app/views/libraries/_index.html.erb
> +    <% @libraries.each do |lib| %>
Même chose qu'en dessous je n'avais pas compris la fonction de locals je vais changer ça ^^

2019-09-04 09:01 UTC, Lodi2244 commented
Concernant le bug ActionController UnknownFormat c'est normal pour le coup pour l'instant le seul format supporté est pdf, je travaille sur mon validator custom pour gérer les exceptions quand le format n'est pas celui attendu

2019-09-04 09:04 UTC, Lodi2244 commented
Concernant le re-naming de ```Library``` en ```Document``` effectivement ce serais plus lisible

2020-02-20 15:59 UTC, merged