Group model
Mate2xo/THP-Creeons_la_coop pull request #222
Opened 2020-09-04 16:41 UTC by Floury-Fabio

2020-10-17 16:09 UTC, Floury-Fabio commented on Gemfile
> +gem 'rails', '~> 5.2'
maj

2020-10-17 16:09 UTC, Floury-Fabio commented on app/admin/groups.rb
> +# rubocop: disable Metrics/BlockLength
rm disable rubocop

2020-10-17 16:09 UTC, Floury-Fabio commented on app/admin/groups.rb
> +# rubocop: enable Metrics/BlockLength
rm enable rubocop

2020-10-17 16:09 UTC, Floury-Fabio commented on app/admin/members.rb
> +  permit_params :email, :password, :encrypted_password, :first_name, :last_name, :biography, :phone_number, :role,
one params per line

2020-10-17 16:09 UTC, Floury-Fabio commented on app/admin/members.rb
> +    column(:group) { |member| member.groups.map(&:name).join(', ') }
add link to groups (view `auto_link` helper)

2020-10-17 16:09 UTC, Floury-Fabio commented on app/admin/members.rb
> +          link_to Arbre::Context.new { (status_tag class: 'important', label: group.name) }, [:admin, group]
test with auto_link

2020-10-17 16:09 UTC, Floury-Fabio commented on app/admin/members.rb
> +             :cash_register_proficiency, :register_id, :biography
one params per line

2020-10-17 16:09 UTC, Floury-Fabio commented on app/models/application_record.rb
> +    return if value.nil?
rm this

2020-10-17 16:09 UTC, Floury-Fabio commented on app/models/group.rb
> +  belongs_to :manager, class_name: :Member, inverse_of: 'managed_group', optional: true
manager has_many managed groups

2020-10-17 16:09 UTC, Floury-Fabio commented on spec/models/member_spec.rb
> +          .class_name('Group').with_foreign_key('manager_id')
has_many

2020-10-17 16:09 UTC, Floury-Fabio commented on spec/models/member_spec.rb
> +      it { is_expected.to accept_nested_attributes_for(:groups).allow_destroy(true) }
change expected.to accept_nested_attributes_for(:groups) to 
expected.to accept_nested_attributes_for(:group_members)

2020-10-17 16:09 UTC, Floury-Fabio commented on spec/models/group_spec.rb
> +      it { is_expected.to have_db_column(:name).of_type(:string).with_options(null: false) }
rm database test

2020-10-17 16:09 UTC, Floury-Fabio commented on spec/models/group_spec.rb
> +      it { is_expected.to belong_to(:manager).class_name('Member').inverse_of('managed_group').optional }
change belong_to to have_many

2020-10-17 16:09 UTC, Floury-Fabio commented on spec/models/group_member_spec.rb
> +
add belongs to member
add belongs to group

2020-10-17 16:09 UTC, Floury-Fabio commented on app/models/member.rb
> +  has_one :managed_group, class_name: 'Group', inverse_of: :manager, foreign_key: 'manager_id', dependent: :nullify
change has_one to has_many

2020-10-17 16:09 UTC, Floury-Fabio commented on app/models/member.rb
> +  accepts_nested_attributes_for :groups, allow_destroy: true
see test comments

2020-10-17 16:09 UTC, Floury-Fabio commented on app/presenters/group_presenter.rb
> +    @group.name.split.join('_')
replace with `#underscore`

2020-10-17 16:09 UTC, Floury-Fabio commented on app/views/members/index.html.erb
> +            <a class="nav-link" href="#<%= presenter.convert_name %>-group" data-toggle="tab" role="tab">
`String.underscore`

2020-10-17 16:09 UTC, Floury-Fabio commented on app/presenters/group_presenter.rb
> +    return @group.manager.id unless @group.manager.nil?
rm this and
manage link presentation with tag.a

2020-10-17 16:09 UTC, Floury-Fabio commented on app/presenters/group_presenter.rb
> +  def manager
replace `#manager` by `#manager_full_name`

2020-10-17 16:09 UTC, Floury-Fabio commented on app/views/members/index.html.erb
> +          <section class="tab-pane fade" id="<%= presenter.convert_name %>-group" role="tabpanel" aria-labelledby="<%= presenter.convert_name %>-group-tab">
`String.underscore`

2020-10-17 16:09 UTC, Floury-Fabio commented on app/views/members/index.html.erb
> +            <div> <%= link_to presenter.manager, member_path(presenter.manager_id) %> </div>
Replace with presenter link helper

2020-10-17 16:09 UTC, Floury-Fabio commented on app/views/members/show.html.erb
> +                  Groupe:
replace `groupe` by `groupes`

2020-10-17 16:09 UTC, Floury-Fabio commented on config/locales/models/group.en.yml
> +        number_of_members: number of members
replace `number_of_members` by `members_count`
rm redondante I18n key

2020-10-17 16:09 UTC, Floury-Fabio commented on config/locales/models/group.fr.yml
> +        number_of_members: nombre de membres
replace number_of_members by members_count

2020-10-17 16:09 UTC, Floury-Fabio commented on create_tempo_table.txt
> +CREATE TABLE tempo_group_table ( number int, name varchar(255));
try to replace `.txt` to `.sql`

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +  FactoryBot.create :member, :admin,
one params per line

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +FactoryBot.create :member, :super_admin,
one params per line

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +    address: FactoryBot.create(:address, :coordinates)
align argument

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +Rails.logger.info 'groups seeded'
Initialize rails logger to output in terminal

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +  addresses: FactoryBot.create_list(:address, rand(1..2)),
align arguments

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +  messageboard_group_id: Thredded::MessageboardGroup.all.sample.id
align argument

2020-10-17 16:09 UTC, Floury-Fabio commented on db/seeds.rb
> +  messageboard: Thredded::Messageboard.all.sample
align argument

2020-10-17 16:09 UTC, Floury-Fabio commented on group_migrate.txt
> +ON members.group = tempo_group_table.number
indent with logical steps

2020-10-17 16:09 UTC, Floury-Fabio commented on insert_group_in_group_table.txt
> +INSERT INTO groups (name, created_at, updated_at)
rename file name into "insert existing groups in new groups table"

2020-10-17 16:09 UTC, Floury-Fabio commented on lib/tasks/migrate_for_new_group_management.rake
> +  file = File.open('insert_group_in_group_table.txt')
rename file name into "insert existing groups in new groups table"

2020-10-17 16:09 UTC, Floury-Fabio commented on lib/tasks/migrate_for_new_group_management.rake
> +  verification
rename `#verification`  to `#check_data_consistency`

2020-10-17 16:09 UTC, Floury-Fabio commented on spec/features/factories_test.rb
> +require 'spec_helper'
rm this line, `spec_helper` is already required by `rails_helper`

2020-10-20 11:13 UTC, Floury-Fabio commented on app/admin/members.rb
> +    column(:group) { |member| member.groups.map(&:name).join(', ') }
Auto link is deprecated

2020-10-20 11:15 UTC, Floury-Fabio commented on app/admin/groups.rb
> +# rubocop: disable Metrics/BlockLength
done

2020-10-20 11:16 UTC, Floury-Fabio commented on app/admin/groups.rb
> +# rubocop: enable Metrics/BlockLength
done

2020-10-20 11:16 UTC, Floury-Fabio commented on app/admin/members.rb
> +  permit_params :email, :password, :encrypted_password, :first_name, :last_name, :biography, :phone_number, :role,
done

2020-10-20 11:16 UTC, Floury-Fabio commented on app/admin/members.rb
> +          link_to Arbre::Context.new { (status_tag class: 'important', label: group.name) }, [:admin, group]
`auto_link` is deprecated

2020-10-20 11:20 UTC, Floury-Fabio commented on app/admin/members.rb
> +             :cash_register_proficiency, :register_id, :biography
done

2020-10-21 09:21 UTC, Floury-Fabio commented on app/models/application_record.rb
> +    return if value.nil?
done

2020-10-21 09:48 UTC, Floury-Fabio commented on spec/models/member_spec.rb
> +      it { is_expected.to accept_nested_attributes_for(:groups).allow_destroy(true) }
We want see and edit relation with groups and not with group_members. We must have to one checkbox per group and for that we need `accept_nested_attributes_for(:groups)`. Active admin create and delete group_members automicaly according to the selection of user.

2020-10-21 09:49 UTC, Floury-Fabio commented on spec/models/group_spec.rb
> +      it { is_expected.to have_db_column(:name).of_type(:string).with_options(null: false) }
done

2020-10-28 08:39 UTC, Floury-Fabio commented on app/models/group.rb
> +  belongs_to :manager, class_name: :Member, inverse_of: 'managed_group', optional: true
done

2020-10-28 08:39 UTC, Floury-Fabio commented on spec/models/member_spec.rb
> +          .class_name('Group').with_foreign_key('manager_id')
done

2020-10-28 08:40 UTC, Floury-Fabio commented on spec/models/member_spec.rb
> +      it { is_expected.to accept_nested_attributes_for(:groups).allow_destroy(true) }
Finally nested resource is useless in our  configuration.

2020-10-28 08:53 UTC, Floury-Fabio commented on spec/models/group_spec.rb
> +      it { is_expected.to belong_to(:manager).class_name('Member').inverse_of('managed_group').optional }
done

2020-10-28 09:07 UTC, Floury-Fabio commented on spec/models/group_member_spec.rb
> +
done

2020-10-28 09:07 UTC, Floury-Fabio commented on app/models/member.rb
> +  has_one :managed_group, class_name: 'Group', inverse_of: :manager, foreign_key: 'manager_id', dependent: :nullify
done

2020-10-28 09:08 UTC, Floury-Fabio commented on app/models/member.rb
> +  accepts_nested_attributes_for :groups, allow_destroy: true
done

2020-10-28 11:34 UTC, Floury-Fabio commented on app/presenters/group_presenter.rb
> +    @group.name.split.join('_')
done

2020-10-28 11:34 UTC, Floury-Fabio commented on app/views/members/index.html.erb
> +            <a class="nav-link" href="#<%= presenter.convert_name %>-group" data-toggle="tab" role="tab">
done

2020-10-28 11:35 UTC, Floury-Fabio commented on app/presenters/group_presenter.rb
> +    return @group.manager.id unless @group.manager.nil?
done with import `link_to` and `_path`

2020-10-28 12:54 UTC, Floury-Fabio commented on app/presenters/group_presenter.rb
> +  def manager
done

2020-10-28 12:54 UTC, Floury-Fabio commented on app/views/members/index.html.erb
> +          <section class="tab-pane fade" id="<%= presenter.convert_name %>-group" role="tabpanel" aria-labelledby="<%= presenter.convert_name %>-group-tab">
done

2020-10-28 12:54 UTC, Floury-Fabio commented on app/views/members/index.html.erb
> +            <div> <%= link_to presenter.manager, member_path(presenter.manager_id) %> </div>
done

2020-10-28 12:57 UTC, Floury-Fabio commented on config/locales/models/group.en.yml
> +        number_of_members: number of members
done

2020-10-28 12:57 UTC, Floury-Fabio commented on config/locales/models/group.fr.yml
> +        number_of_members: nombre de membres
done

2020-10-28 13:14 UTC, Floury-Fabio commented on create_tempo_table.txt
> +CREATE TABLE tempo_group_table ( number int, name varchar(255));
done

2020-10-28 13:20 UTC, Floury-Fabio commented on db/seeds.rb
> +  FactoryBot.create :member, :admin,
done

2020-10-28 13:20 UTC, Floury-Fabio commented on db/seeds.rb
> +FactoryBot.create :member, :super_admin,
done

2020-10-28 13:20 UTC, Floury-Fabio commented on db/seeds.rb
> +    address: FactoryBot.create(:address, :coordinates)
done

2020-10-28 14:13 UTC, Floury-Fabio commented on db/seeds.rb
> +Rails.logger.info 'groups seeded'
done

2020-10-28 14:13 UTC, Floury-Fabio commented on db/seeds.rb
> +  addresses: FactoryBot.create_list(:address, rand(1..2)),
done

2020-10-28 14:13 UTC, Floury-Fabio commented on db/seeds.rb
> +  messageboard_group_id: Thredded::MessageboardGroup.all.sample.id
done

2020-10-28 14:13 UTC, Floury-Fabio commented on db/seeds.rb
> +  messageboard: Thredded::Messageboard.all.sample
done

2020-10-28 14:13 UTC, Floury-Fabio commented on group_migrate.txt
> +ON members.group = tempo_group_table.number
done

2020-10-28 14:20 UTC, Floury-Fabio commented on insert_group_in_group_table.txt
> +INSERT INTO groups (name, created_at, updated_at)
done

2020-10-28 14:21 UTC, Floury-Fabio commented on lib/tasks/migrate_for_new_group_management.rake
> +  file = File.open('insert_group_in_group_table.txt')
done

2020-11-04 19:10 UTC, Mate2xo requested changes

2020-11-04 19:10 UTC, Mate2xo commented on app/admin/groups.rb
> +    column(:managers) do |managed_group|
Rename `managed_group` to `group`

2020-11-04 19:10 UTC, Mate2xo commented on app/admin/groups.rb
> +      group_links = managed_group.managers.map { |manager| auto_link manager }
rename `group_links` to `managers_list`

2020-11-04 19:10 UTC, Mate2xo commented on app/admin/groups.rb
> +    column(I18n.t('activerecord.attributes.group.number_of_members')) { |group| group.members.size }
use I18n lookup shortcut `t('.members_count')`

2020-11-04 19:10 UTC, Mate2xo commented on app/admin/groups.rb
> +        column 'members' do |member|
use I18n :
`Member.model_name.human`

2020-11-04 19:10 UTC, Mate2xo commented on app/admin/groups.rb
> +        column 'managers' do |manager|
I18n:
`resource.class.human_attribute_name(:managers)`

2020-11-04 19:10 UTC, Mate2xo commented on app/admin/members.rb
> +    column(:group) { |member| member.groups.map(&:name).join(', ') }
Remove duplicate column

2020-11-04 19:10 UTC, Mate2xo commented on app/presenters/group_presenter.rb
> +    @group.name.split.join('_')
https://devdocs.io/rails~5.2/string#method-i-underscore (doesn't replaces spaces)

2020-11-04 19:10 UTC, Mate2xo commented on spec/factories/group_managers.rb
> +    manager { nil }
Check if `belongs_to` validations are effective (?)

2020-11-04 19:10 UTC, Mate2xo commented on spec/factories/group_members.rb
> +  end
Same as above, check if foreign keys validations are ok

2020-11-05 14:09 UTC, Floury-Fabio commented
https://github.com/Mate2xo/Creeons_la_coop/issues/218

2020-11-06 12:39 UTC, Mate2xo approved these changes

2020-11-10 12:21 UTC, merged