Private documents
Mate2xo/THP-Creeons_la_coop pull request #235
Opened 2020-10-30 16:39 UTC by Floury-Fabio

2020-11-06 14:21 UTC, Floury-Fabio commented
https://github.com/Mate2xo/Creeons_la_coop/issues/224

2020-11-09 18:26 UTC, Mate2xo requested changes

2020-11-09 18:26 UTC, Mate2xo commented on db/schema.rb
> +    t.boolean "exposed"
Si c'est ok pour toi, je pense que renommer cet attribut en `public` serait plus explicite. T'en penses quoi?

2020-11-09 18:26 UTC, Mate2xo commented on app/policies/document_policy.rb
> +
Si tu fais ça, personne à part les admins ne pourra voir les documents.
Tout les membres doivent avoir accès aux documents, puliques ou 'privés' (= 'internes')
Les documents 'publiques' sont visibles pour les utilisateurs non loggés il me semble

2020-11-09 18:26 UTC, Mate2xo commented on app/controllers/infos_controller.rb
> +    @infos = Info.all.order(:id)
Je crois que cette variable `@infos` n'est même plus utilisée dans la vue. Il y a une raison pour laquelle tu as eu besoin de faire ça?

Sinon je pense que c'est l'occasion de déplacer tout ce code concernant les documents dans le `documents_controller`, et donc gérér l'index là-bas. Donc aussi changer le routing comme il faut.
On pourra recycler plus tard cet `infos_controller` pour la mise en place du blog dans une prochaine feature.

2020-11-09 18:26 UTC, Mate2xo commented on app/views/documents/_document.html.erb
> +<tr name="document#{document.id} row">
Est-ce que la string ` row` est censée être dans un attribut `class="..."`? Ou est-ce que c'est une typo?

Je suppose que l'attribut `name="..."` est là pour être ciblé par les requêtes en AJAX, dans ce cas il est peut-être plus conventionnel de le mettre dans un attribut `id="..."`

2020-11-09 18:26 UTC, Mate2xo commented on app/views/documents/_document.html.erb
> +      <% end %>
Tu peux faire `<%= document.exposed ? oui : non %>`

2020-11-09 18:26 UTC, Mate2xo commented on app/views/documents/_document.html.erb
> +      <% end %>
Tu pourrais mettre ça dans un view helper du style `publish_action(document)`, ça éviterait les if dans les if peu lisibles, tout en transmettant le message suffisant "ici c'est l'action pour publier/dépublier un doc"

Comme tout le code est identique à part le `publish/unpublish` tu pourrais y déterminer sa valeur avec une variable.
ex:
```ruby
return unless policy(document).update? # document en minuscule pour passer l'objet authorisé par le controller

translation_scope = %i[main_app views application buttons]
link_name = document.exposed ? 'unpublish' : 'publish'
link_to t(link_name, scope: translation_scope),
        document_path(document, exposed: !document.expose),
        method: :put,
        id: document.id,
        class: 'btn btn-mini btn-warning',
        data: { remote: true }
```

2020-11-09 18:26 UTC, Mate2xo commented on app/views/documents/update.js.erb
> +}
Il serait mieux d'avoir ces strings `'oui'`, `'non'`, `'Publier'` et `'Dépublier'` dans des locales I18n. Ainsi ça éviterait que je JS saute si on décide de changer ces textes pour une raison ou une autre.
Les textes des boutons sont déjà dans des locales en plus

2020-11-10 07:02 UTC, Floury-Fabio commented on db/schema.rb
> +    t.boolean "exposed"
(You can continue to speak English, i need to train my english)

I agree with you but, doesn't public is a keyword of rails ?

2020-11-10 07:33 UTC, Floury-Fabio commented on app/controllers/infos_controller.rb
> +    @infos = Info.all.order(:id)
From my memory the partials document are call in info index view. I followed the current structure. I will rewrite this structure in order to call only document resource.

2020-11-10 08:07 UTC, Floury-Fabio commented on db/schema.rb
> +    t.boolean "exposed"
published

2020-12-30 07:20 UTC, Mate2xo commented
Is there any update on this branch? The conflicts also need to be addressed

2021-02-01 12:42 UTC, Floury-Fabio commented
this feature is realized in https://github.com/Mate2xo/Creeons_la_coop/pull/282

2021-02-01 12:42 UTC, closed without merging