desactivate confirmation for email update
Mate2xo/THP-Creeons_la_coop pull request #238
Opened 2020-11-09 08:50 UTC by Floury-Fabio

2020-11-09 08:53 UTC, Floury-Fabio commented
The title tells all.

2020-11-09 09:56 UTC, Mate2xo requested changes
This will deactivate email change confirmations for ALL users.
We only want to have this mail confirmation for 'inactive' users.

With this change, a regular user that wants to change his/her own mail address from his/her profile won't receive any mail confirmation. Thus if the user makes a mistake, he/she won't be able to login anymore

2020-11-10 18:09 UTC, Mate2xo requested changes
Just add a controller/request test to frame this particular case and we'll be good to go

2020-11-11 09:48 UTC, Floury-Fabio commented
https://github.com/Mate2xo/Creeons_la_coop/issues/231

2020-11-11 10:32 UTC, Mate2xo requested changes

2020-11-11 10:32 UTC, Mate2xo commented on spec/controllers/members_controller_spec.rb
> +      it "don't update the email directly" do
`dont't` -> `doesn't`

2020-11-11 10:32 UTC, Mate2xo commented on app/admin/members.rb
>          failure.html { render :edit }
You have to use either `|format|` or `|success, failure|` (see [inherited resources](https://github.com/activeadmin/inherited_resources#overwriting-actions))
Here, `failure.html { render :edit }` will actually be rendered whether the update is a failure or not

2020-11-11 12:46 UTC, Mate2xo approved these changes

2020-11-11 12:54 UTC, merged