Static planning restoration
Mate2xo/THP-Creeons_la_coop pull request #263
Opened 2021-01-02 16:49 UTC by Floury-Fabio

2021-01-02 17:04 UTC, Floury-Fabio commented
This branch add:
- A StaticSlot model  in order to attribute static time slot at members
- A ScheduleGenerator services
- A Recruiter services who enrolls automatically the members who have a static slot

2021-01-02 17:16 UTC, Floury-Fabio commented
This branch add:
- StaticSlot model who represent a time slot in a cycle of 4 weeks
- A ScheduleGenerator services
- A Recruiter services who enrolls the members who have a static_slot

2021-01-02 18:12 UTC, Mate2xo requested changes

2021-01-02 18:12 UTC, Mate2xo commented on app/admin/members.rb
> +    f.input :static_slots, as: :check_boxes, collection: StaticSlot.all.map { |static_slot| [static_slot.decorate.full_display, static_slot.id] }
Decorate the collection once rather than decorate all the individual elements one at a time.
Draper offers a method for that (I think it's the usual `.decorate` but you can use it like this: `StaticSlot.all.decorate.map {...}`). This will give you exactly the same result, but is better performance-wise

2021-01-02 18:12 UTC, Mate2xo commented on app/admin/members.rb
> +    redirect_to admin_member_path(member), notice: 'success'
Did you mean ` notice : t('.success')` ?

2021-01-02 18:12 UTC, Mate2xo commented on app/admin/missions.rb
> +  end
``` ruby
feedback_message = generated ? t('.schedule_generation_in_progress') : t('.schedule_already_generated')

redirect_to admin_missions_path, notice: feedback_message
```

2021-01-02 18:12 UTC, Mate2xo commented on app/admin/static_slots.rb
> +# StaticSlot is an attributes of member and enable the auto enrollment
`# A StaticSlot belongs to a Member, and allows a member to enroll automatically each month to the Mission that this StaticSlot refers to`

2021-01-02 18:12 UTC, Mate2xo commented on app/jobs/generate_schedule_job.rb
> +  def perform(*args)
Since you only use the first argument on `#perform`, can't you name it?
e.g.:  
```ruby
def perform(params)
  schedule_generator = ScheduleGenerator.new(params[:current_member], params[:current_month].to_datetime)
  ...
```

2021-01-02 18:12 UTC, Mate2xo commented on app/models/history_of_generated_schedule.rb
> +# This model retains the months for which a schedule had been generated
Why?
` [...]. This allows us to allow or prevent the launch of a GenerateScheduleJob : if no schedule has been created for a given month, we allow the GenerateScheduleJob to launch`

2021-01-02 18:12 UTC, Mate2xo commented on app/models/history_of_static_slot_selection.rb
> +# It serves to prevent the abuses by the members.
`'# It is used to ...'`

2021-01-02 18:12 UTC, Mate2xo commented on app/services/schedule_generator.rb
> +# It generates a planning for the a month
`# Generates a set of common missions for a given month. This allows admins not having to create the same kind of missions over and over again. This service is similar to the RecurrentMission generator, but it is intended to be used in a Job rather than from the UI`

2021-01-02 18:12 UTC, Mate2xo commented on app/services/static_members_recruiter.rb
> +# It enroll members with static slots to the related missions
`# Fetches all existing StaticSlots, and enrolls the associated Member to the associated Mission on a given StaticSlot start_time`

2021-01-02 18:12 UTC, Mate2xo commented on app/services/static_members_recruiter.rb
> +
`private` ?

2021-01-02 18:12 UTC, Mate2xo commented on app/transactions/members/update_transaction.rb
> +    tee :extract_ids
`tee :extract_static_slots_ids`

2021-01-02 18:12 UTC, Mate2xo commented on app/transactions/members/update_transaction.rb
> +  # extract member selection and update in order to attribute static slots
`# extracts a member's static slot selection, assigns the selected static slots, and updates the member`

2021-01-02 18:12 UTC, Mate2xo commented on config/locales/active_admin.fr.yml
> +        confirm_enroll_static_members: 'Êtes_vous sûr de vouloir inscrire les membres fixes'
Êtes_vous sûr de vouloir inscrire les membres fixes `?`

2021-01-02 18:12 UTC, Mate2xo commented on config/locales/views/mission.en.yml
> +        schedule_already_generated: All schedules asked have already generated.
These schedules have already been generated

2021-01-02 18:12 UTC, Mate2xo commented on spec/factories/history_of_generated_schedules.rb
> +
Isn't the `:month` a required attribute?

2021-01-03 12:02 UTC, Mate2xo approved these changes

2021-01-03 12:07 UTC, merged