Feedback from jobs
Mate2xo/THP-Creeons_la_coop pull request #287
Opened 2021-02-15 14:20 UTC by Floury-Fabio

Add action cable channel in order to generate notifications after the enroll static members job.

-

2021-03-23 18:49 UTC, Mate2xo requested changes

2021-03-23 18:49 UTC, Mate2xo commented on app/services/static_members_recruiter.rb
> +  def find_mission_with_adequate_cash_register_requirement(member, missions, time_slot)
`def find_adequate_mission_or_send_error_report(...)`

2021-03-23 18:49 UTC, Mate2xo commented on app/transactions/members/update_transaction.rb
> +    tee :enroll_member_according_to_new_static_slots
`    tee :enroll_member_according_to_new_static_slots_or_send_error_report`

2021-03-23 18:49 UTC, Mate2xo commented on app/assets/javascripts/application.js
> +//= require i18n/translations
Is this really necessary as we use js translation only in the admin interface? Delete it otherwise

2021-03-23 18:49 UTC, Mate2xo commented on app/assets/javascripts/channels/notifications.js
> +                  <p> ${I18n.t('admin.members.js.end_of_auto_enrollment')} </p>
If this is the only place that you use I18n in JS, you could maybe try to rename this file into `notifications.js.erb` and see if the asset pipeline compiles it properly.
If it does, then you could do
```
                  <p> <%= I18n.t('admin.members.js.end_of_auto_enrollment') %> </p>
```
and get rid of the `i18n-js` gem entirely

2021-03-23 18:49 UTC, Mate2xo commented on spec/models/static_members_recruiter_service_spec.rb
> +  context 'when all static slots of all members has a corresponding time slot in missions' do
`  context 'when all static slots of all members have been assigned to a corresponding time slot in the upcoming missions' do`

2021-03-23 18:49 UTC, Mate2xo commented on spec/models/static_members_recruiter_service_spec.rb
> +  context 'when a static slots of one member has not a corresponding time slot in missions' do
` context 'when a static slot of a given member has no available time slot in upcoming missions' do`

2021-03-23 18:49 UTC, Mate2xo commented on spec/models/static_members_recruiter_service_spec.rb
> +    it 'The recruiter has no reports' do
Copy/paste fail :1st_place_medal:

2021-03-24 16:45 UTC, Floury-Fabio commented on spec/models/static_members_recruiter_service_spec.rb
> +    it 'The recruiter has no reports' do
:)

2021-03-25 12:02 UTC, Mate2xo approved these changes

2021-03-25 12:02 UTC, Mate2xo commented on app/admin/members.rb
> +    # We must wait the end of page reload for keep job notifications
`    # We must wait the end of page reload from the redirection. Otherwise if the job finishes before the page reload, the user won't get the 'job finished' notification from ActionCable`

2021-03-28 21:51 UTC, merged